# Generated by Django 3.0.4 on 2020-07-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIHRE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='result2',
            new_name='dbms1',
        ),
    ]
