# Generated by Django 3.0.4 on 2020-07-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIHRE', '0002_auto_20200724_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbms1',
            old_name='output',
            new_name='pt_id',
        ),
        migrations.RenameField(
            model_name='dbms1',
            old_name='pateint_id',
            new_name='pt_name',
        ),
        migrations.RenameField(
            model_name='dbms1',
            old_name='patient_name',
            new_name='pt_output',
        ),
    ]
