# Generated by Django 3.0.8 on 2020-07-29 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SIHRE', '0003_auto_20200724_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbms1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
